[tool.poetry]
name = "iscc-registry"
version = "0.1.0"
description = ""
authors = ["titusz <tp@py7.de>"]

[tool.poetry.dependencies]
python = "^3.6"
vyper = "^0.2.3"

[tool.poetry.dev-dependencies]
pytest = "^5.0"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
